version: '3.4'

services:
  crispycollab:
    image: ${DOCKER_REGISTRY-}crispycollab
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "sqlserver"
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y
