version: '3.4'
name: crispycollab

services:
  sqlserver:
    container_name: SQLServer
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y
    volumes:
      - sqlserver:/sqlserver
volumes: 
  sqlserver:
