version: '3.4'
name: CrispyCollab-Web

services:
  crispycollab:
    container_name: CrispyCollab
    build:
      context: .
      dockerfile: /Source/Web/WebServer/Dockerfile
      tags:
        - latest
