version: '3.4'
name: CrispyCollab

services:
  sqlserver:
    container_name: SQLServer
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y
    volumes:
      - sqlserver:/sqlserver
  redis:
    container_name: RedisCache
    image: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=@someThingComplicated1234
    volumes:
      - redis:/redis
volumes: 
  sqlserver:
  redis: