name: CrispyCollab Build and Test

on:
  push:
    branches:
      - main
    pull_request:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        dotnet-version: 6.0.x
        name: build-artifacts
        path: BuildArtifacts
        # Use always() to always run this step to publish test results when there are test failures
        if: always()

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifacts from build job
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
    - name: Test
      run: dotnet test --verbosity normal
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        dotnet-version: 6.0.x
        name: dotnet-results
        path: TestResults
        # Use always() to always run this step to publish test results when there are test failures
        if: always()