name: CrispyCollab Build and Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --results-directory "TestResults"
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: Test-Results
        path: TestResults
        # Use always() to always run this step to publish test results when there are test failures
        if: always()
        retention-days: 1
    - name: Publish
      run: dotnet publish --configuration release --output './published-app' ${{ github.workspace }}/Source/Web/Server/Web.Server.csproj
    - name: Upload Publish Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Published-Artifacts
        path: './published-app'

  deploy_dev:
    needs: build_test
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: Published-Artifacts
        path: './published-app'
